### ISSUE TITLE
Todo List

### ISSUE THREAD

**Issue by RodrigoVidotti** [vitor27melo/MAC439-SAS-FrontEnd#2]
# Infra

- [x] Criar configuração para conexão com o PostrgreSQL
- [ ] Criar configuração para conexão com o Redis
- [ ] Criar configuração para conexão com o MongoDB
- [ ] Criar configuração para conexão com o Neo4J

# Backend

- [ ] Refatorar scans de rows para alguma forma genérica (colocar em algum tipo de helper)
- [x] Refatorar rotas para algum arquivo routes
- [ ] Refatorar métodos para controllers (ou algo parecido)

# Frontend

- [ ]
